version: '3.7'


services:
  api:
    build: ./backend
    command: python app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./.env

  telegram_bot:
    build: ./telegram_bot
    command: python app/main.py runserver
    volumes:
      - .:/code
    depends_on:
      - postgres
    env_file:
      - ./.env
  
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - 5432:5432
    

volumes:
  postgres_data: