version: '3.7'


services:
  api:
    build: ./backend
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres
    env_file:
      - ./.env

  telegram_bot:
    build: ./telegram_bot
    command: python telegram_bot/main.py runserver
    volumes:
      - .:/code
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
    env_file:
      - ./.env

volumes:
  postgres_data: